CREATE TABLE [dbo].[Farm]
(
	[FarmID] BIGINT NOT NULL PRIMARY KEY IDENTITY ,
	[UserID] BIGINT NOT NULL,
	[FarmName] VARCHAR(50) NOT NULL,
	[LastModifiedID] INT NULL,
	[TMStamp] DATETIME, 
    CONSTRAINT [FK_Farm_ToUser] FOREIGN KEY (UserID) REFERENCES [User]([UserID]) 
)
