CREATE TABLE [dbo].[Farm]
(
	[FarmID] BIGINT NOT NULL PRIMARY KEY IDENTITY ,
	[UserID] BIGINT NOT NULL,
	[FarmName] VARCHAR(50) NOT NULL,
	[LastModifiedID] SYSNAME DEFAULT CURRENT_USER NOT NULL,
	[TMStamp] DATETIME DEFAULT GETDATE() NOT NULL	
    CONSTRAINT [FK_Farm_ToUser] FOREIGN KEY (UserID) REFERENCES [User]([UserID]) ON DELETE CASCADE
)
