CREATE TABLE [dbo].[ScoutBug]
(
	[ScoutBugID] BIGINT NOT NULL PRIMARY KEY IDENTITY ,
	[ScoutStopID] BIGINT NOT NULL,
	[SpeciesID] BIGINT NOT NULL,
	[NumberOfBugs] INT NOT NULL,
	[FieldPicture] VARBINARY(MAX) NOT NULL,
	[Comments] VARCHAR(500),
	[LastModifiedID] SYSNAME DEFAULT CURRENT_USER NOT NULL,
	[TMStamp] DATETIME DEFAULT GETDATE() NOT NULL	
	CONSTRAINT [FK_ScoutBug_ToScoutStop] FOREIGN KEY ([ScoutStopID]) REFERENCES [ScoutStop]([ScoutStopID]) ON DELETE CASCADE,
	CONSTRAINT [FK_ScoutBug_ToSpecies] FOREIGN KEY ([SpeciesID]) REFERENCES [Species]([SpeciesID])
)
