CREATE TABLE [dbo].[User]
(
	[UserID] BIGINT NOT NULL PRIMARY KEY IDENTITY,
	[Email] VARCHAR(50) NOT NULL,
	[Password] VARCHAR(20) NOT NULL,
	[LastModifiedID] SYSNAME DEFAULT CURRENT_USER NOT NULL,
	[TMStamp] DATETIME DEFAULT GETDATE() NOT NULL	
)
