CREATE TABLE [dbo].[User]
(
	[UserID] INT NOT NULL PRIMARY KEY IDENTITY,
	[RoleID] INT NOT NULL,
	[Email] VARCHAR(50) NOT NULL,
	[Password] VARCHAR(20) NOT NULL,
	[LastModifiedID] INT NULL,
	[TMStamp] DATETIME,
	CONSTRAINT [FK_User_ToRole] FOREIGN KEY ([RoleID]) REFERENCES [Role]([RoleID])
)
