//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevicePushNotification
    {
        public long Id { get; set; }
        public long UserID { get; set; }
        public string RegID { get; set; }
    
        public virtual User User { get; set; }
    }
}
